---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cyclops.sakshitposting-irl.github.io
  resources:
  - certreports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cyclops.sakshitposting-irl.github.io
  resources:
  - certreports/finalizers
  verbs:
  - update
- apiGroups:
  - cyclops.sakshitposting-irl.github.io
  resources:
  - certreports/status
  verbs:
  - get
  - patch
  - update
