apiVersion: cyclops.sakshitposting-irl.github.io/v1alpha1
kind: CertReport
metadata:
  labels:
    app.kubernetes.io/name: cyclops
    app.kubernetes.io/managed-by: kustomize
  name: certreport-sample
spec:
  # TODO(user): Add fields here
